# Generated by Django 3.1.3 on 2021-01-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210124_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=7),
        ),
    ]
