# Generated by Django 3.1.3 on 2021-04-16 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210412_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 30, 36, 363019)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(default=datetime.time(21, 30, 36, 363019)),
        ),
    ]
