# Generated by Django 3.1.3 on 2021-04-17 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210417_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 8, 0, 844348)),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.TimeField(default=datetime.time(21, 8, 0, 844348)),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=255)),
                ('message', models.TextField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
