# Generated by Django 3.1.3 on 2021-01-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(default='face_images/default.jpg', upload_to='face_images/'),
        ),
    ]
