# Generated by Django 3.1.3 on 2021-01-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_face_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
