# Generated by Django 3.1.3 on 2021-01-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('account', '0005_auto_20210106_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='study_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
