# Generated by Django 3.1.3 on 2021-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210106_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(default='', max_length=255),
        ),
    ]
