# Generated by Django 3.1.3 on 2021-01-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True),
        ),
    ]
