# Generated by Django 3.1.3 on 2021-01-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210123_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
